---
title: Archetype Media
timezone: Australia/Melbourne
collections:
  advertisers:
    title: Advertisers
    output: false
  contacts:
    title: Contacts
    output: false
  posts:
    title: Posts
    output: true
  publishers:
    title: Publishers
    output: false
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: work
  values:
    link: ''
    image: ''
    subtitle: ''
- scope:
    path: ''
    type: publishers
  values:
    link: ''
    image: ''
    subtitle: ''
- scope:
    path: ''
    type: contacts
  values:
    title: ''
    phone: ''
    email: ''
livereload: true
permalink: pretty
