---
title: Archetype Media
timezone: Australia/Melbourne
collections:
  contacts:
    title: Contacts
    output: false
  partners:
    title: Partners
    output: false
  posts:
    title: Posts
    output: true
  publishers:
    title: Publishers
    output: false
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: work
  values:
    link: ''
    image: ''
    subtitle: ''
- scope:
    path: ''
    type: publishers
  values:
    link: ''
    image: ''
    subtitle: ''
- scope:
    path: ''
    type: contacts
  values:
    role: ''
    phone: ''
    email: ''
address: 19–21 Johnston St<br/>Collingwood, VIC, 3065
phone: 0312 3456 7890
email: sales@archetypemedia.com.au
copyright: Archetype Media<br/>Copyright &copy; 2017
livereload: true
permalink: pretty
exclude:
- Gruntfile.js
- webpack.config.js
- Gemfile.lock
- Gemfile
- package.json
- README*
- node_modules
- ".gitignore"
- assets/scripts/src
- yarn.lock
- ".git"
gems:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: assets/styles/
  style: compressed
