---
title: Archetype Media
timezone: Australia/Melbourne
livereload: true
collections:
  advertisers:
    title: Advertisers
    output: true
  posts:
    title: Posts
    output: true
  publishers:
    title: Publishers
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: 'work'
  values:
    link: ''
permalink: pretty
